### ISSUE TITLE
[PARENT - METERING]: Saturn Metering

### ISSUE THREAD

**Issue by tchardin** [filecoin-saturn/roadmap#31]
Tasks:
- [x] filecoin-saturn/roadmap#32 
- [x] filecoin-saturn/roadmap#33 
- [x] https://github.com/filecoin-saturn/browser-client/issues/19
- [x] https://github.com/filecoin-saturn/L1-node/issues/494
- [x] https://github.com/filecoin-saturn/log-ingestor/issues/104

REMAINING STEPS (in order)
- [x] filecoin-saturn/browser-client#22 (11/1)
- [x] Ansgar reaching out to metaplex today (11/1)
- [x] create account for arc (11/1), get client key, add this to arc, deploy arc (Thomas)
- [ ] Subvisual landing invite code box (11/2)
- [ ] Portal w/ invite code deploy to prod (tracked elsewhere) (hopefully 11/2)
- [x] Deploy new L1 code w/ auth to Staging (11/2)
- [x] https://github.com/filecoin-saturn/orchestrator/issues/237
- [ ] filecoin-saturn/roadmap#49 (11/3)
- [ ] Deploy prod terraform to add L1 JWT to orch secrets
- [ ] Deploy prod orchestrator to add JWT to L1 CID requests
- [ ] Deploy L1 w/ auth to Canary (11/6)
- [ ] Run tests (11/6)
- [ ] https://github.com/filecoin-saturn/L1-node/issues/505
- [ ] filecoin-saturn/roadmap#48
- [ ] (When auth is required) Deploy prod calculator lambda with the jwt verification feature flag removed.

@tchardin and @guanzo are working on this

**Comment by guanzo** [comment]
I can do any of these. Once you figure out the priority, feel free to assign me a ticket.

**Comment by reidlw** [comment]
Per @tchardin - everything but #104 done this week, 104 next week.

**Comment by hannahhoward** [comment]
awaiting merge of JWT blocking on getting filecoin-saturn/browser-client#22 and #51

**Comment by guanzo** [comment]
Staging instance is live: https://portal.saturn-test.network/

For prod:
* Someone needs to fill out the business details (bank account, etc) on Stripe before we can receive the production API keys 
   * https://dashboard.stripe.com/account/onboarding/business-structure
* AWS SES (Simple Email Service) needs to be setup.
  * Should we use an email other than `saturn@protocol.ai` for the portal? For emails that are sent by the portal, the email that we display to customers, etc.

**Comment by reidlw** [comment]
We're going to ask Subvisual to hold on re-enabling things (disabledd currently due to fallback bug) until early next week when all components of auth flow are deployed to prod

**Comment by reidlw** [comment]
1. @guanzo is going to go in the back-end and manually create a client key we can use to deploy the service worker out to Arc
2. @AmeanAsad will jump in on client deploy to arc with the new key
3. @guanzo deploy L1 to staging

**Comment by guanzo** [comment]
> @guanzo is going to go in the back-end and manually create a client key we can use to deploy the service worker out to Arc
> @AmeanAsad will jump in on client deploy to arc with the new key
> @guanzo deploy L1 to staging

These are all done.

**Comment by guanzo** [comment]
Realized that orch now requires a JWT for L1 requests. I added this issue to the tracker https://github.com/filecoin-saturn/orchestrator/issues/237

**Comment by guanzo** [comment]
11/3 Update:

> Realized that orch now requires a JWT for L1 requests. I added this issue to the tracker https://github.com/filecoin-saturn/orchestrator/issues/237

* This is now resolved, all testnet nodes back online

* Updated js-client and browser-client, the customer fallback logic is now working.

**Comment by reidlw** [comment]
Feel it should be okay to close this now, as we're using other mechanisms to track the testing and delivery of this feature set
